"""Module-boundary detection for the py-shiny app subprocess.

py-shiny's module system (`shiny.module.ui`/`shiny.module.server`, both
routed through `namespace_context()`) is the counterpart to R's
`shiny::moduleServer()`. R records boundaries by hooking `moduleServer()`
inside the Shiny *child* process (via its bootstrap); py-shiny apps run in a
subprocess separate from the pytest session, so the Python equivalent writes
a `sitecustomize.py` into `.shiny.cov/` and puts that directory on
`PYTHONPATH`. The subprocess's `site` module imports `sitecustomize` at
startup, which wraps `namespace_context()` and writes the resolved prefixes
to `.shiny.cov/modules.json` -- the same ground-truth shape R's hook produces.
"""
from __future__ import annotations

import json
import os
import pathlib
from typing import Any

SITE_CUSTOMIZE = '''# Generated by shinycov. Records py-shiny module namespaces to modules.json.
import json
import os
from contextlib import contextmanager

_OUT_DIR = os.environ.get("SHINYCOV_OUTPUT_DIR", "")
_BOUNDARIES = set()


def _flush():
    if not _OUT_DIR:
        return
    try:
        os.makedirs(_OUT_DIR, exist_ok=True)
        with open(os.path.join(_OUT_DIR, "modules.json"), "w") as fh:
            json.dump(sorted(_BOUNDARIES), fh)
    except OSError:
        pass


try:
    import shiny.module as _shiny_module
    from shiny._namespaces import current_namespace

    _original = _shiny_module.namespace_context

    @contextmanager
    def _wrapped(module_id):
        with _original(module_id):
            namespace = current_namespace()
            if namespace:
                _BOUNDARIES.add(str(namespace))
                _flush()
            yield

    _shiny_module.namespace_context = _wrapped
except Exception:
    pass
'''


def install(out_dir: str | pathlib.Path) -> pathlib.Path:
    """Install the subprocess hook into `out_dir` and expose it via env vars.

    Writes `sitecustomize.py` (the hook source) and sets `PYTHONPATH` plus
    `SHINYCOV_OUTPUT_DIR` so the app subprocess imports the hook at startup
    and knows where to write `modules.json`.
    """
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "sitecustomize.py").write_text(SITE_CUSTOMIZE, encoding="utf-8")

    existing = os.environ.get("PYTHONPATH", "")
    os.environ["PYTHONPATH"] = (
        str(out_dir) + (os.pathsep + existing if existing else "")
    )
    os.environ["SHINYCOV_OUTPUT_DIR"] = str(out_dir)
    return out_dir


def read_boundaries(out_dir: str | pathlib.Path) -> list[str]:
    """Read the module boundaries written by the app subprocess hook."""
    path = pathlib.Path(out_dir) / "modules.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []
    return data if isinstance(data, list) else []


def attach_boundaries(
    snapshot: dict[str, Any], boundaries: list[str]
) -> dict[str, Any]:
    """Populate a manifest's `modules` and each element's `module` field.

    Longest-prefix match against the recorded boundaries, the same
    attribution R's `apply_module_boundaries()` performs. R's corroboration
    check (a lone id that merely shares a real module's prefix) is
    deliberately not ported: it only affects cosmetic grouping in a rare
    top-level-id-coincidence case.
    """
    if not boundaries:
        return snapshot
    ordered = sorted(set(boundaries), key=len, reverse=True)

    def owning(element_id: str) -> str:
        for boundary in ordered:
            if element_id == boundary or element_id.startswith(boundary + "-"):
                return boundary
        return ""

    snapshot["modules"] = sorted(set(boundaries))
    for element in snapshot.get("inputs", []):
        element["module"] = owning(element.get("id") or "")
    for element in snapshot.get("outputs", []):
        element["module"] = owning(element.get("id") or "")
    return snapshot
