"""Module-boundary detection for the py-shiny app subprocess.

py-shiny's module system (`shiny.module.ui`/`shiny.module.server`, both
routed through `namespace_context()`) is the counterpart to R's
`shiny::moduleServer()`. R records boundaries by hooking `moduleServer()`
inside the Shiny *child* process (via its bootstrap); py-shiny apps run in a
subprocess separate from the pytest session, so the Python equivalent writes
a `sitecustomize.py` into `.shiny.cov/` and puts that directory on
`PYTHONPATH`. The subprocess's `site` module imports `sitecustomize` at
startup, which wraps `namespace_context()` and writes the resolved prefixes
to `.shiny.cov/modules.json` -- the same ground-truth shape R's hook produces.
"""
from __future__ import annotations

import json
import os
import pathlib
from typing import Any

SITE_CUSTOMIZE = '''# Generated by shinycov. Records py-shiny module namespaces and per-line
# hit counts (execution counts) to .shiny.cov/, using sys.monitoring so it
# coexists with coverage.py's own sys.settrace-based tracing.
import atexit
import json
import os
import signal
import sys
from contextlib import contextmanager

_OUT_DIR = os.environ.get("SHINYCOV_OUTPUT_DIR", "")
_APP_DIR = os.path.dirname(os.path.abspath(_OUT_DIR)) if _OUT_DIR else ""
_SOURCE = os.environ.get("SHINYCOV_SOURCE", "pytest")
_BOUNDARIES = set()
_HITS = {}  # (filename, lineno) -> count


def _flush():
    if not _OUT_DIR:
        return
    try:
        os.makedirs(_OUT_DIR, exist_ok=True)
        with open(os.path.join(_OUT_DIR, "modules.json"), "w") as fh:
            json.dump(sorted(_BOUNDARIES), fh)
        with open(os.path.join(_OUT_DIR, f"linehits.{_SOURCE}.json"), "w") as fh:
            json.dump({f"{fn}:{ln}": count for (fn, ln), count in _HITS.items()}, fh)
    except OSError:
        pass


_prev_handlers = {}


def _on_signal(signum, frame):
    _flush()
    prev = _prev_handlers.get(signum)
    if prev is not None and prev not in (signal.SIG_DFL, signal.SIG_IGN):
        prev(signum, frame)  # chain (e.g. coverage.py's sigterm handler)
    else:
        signal.signal(signum, signal.SIG_DFL)
        os.kill(os.getpid(), signum)


for _sig in (signal.SIGTERM, signal.SIGINT):
    try:
        _prev_handlers[_sig] = signal.getsignal(_sig)
        signal.signal(_sig, _on_signal)
    except (ValueError, OSError):
        pass

atexit.register(_flush)


try:
    import shiny.module as _shiny_module
    from shiny._namespaces import current_namespace

    _original = _shiny_module.namespace_context

    @contextmanager
    def _wrapped(module_id):
        with _original(module_id):
            namespace = current_namespace()
            if namespace:
                _BOUNDARIES.add(str(namespace))
                _flush()
            yield

    _shiny_module.namespace_context = _wrapped
except Exception:
    pass


try:
    from sys import monitoring as _mon

    def _line_cb(code, lineno):
        filename = code.co_filename
        # <frozen ...>/<string>/... have no real path; abspath would prepend
        # the cwd and wrongly match _APP_DIR.
        if filename.startswith("<"):
            return
        filename = os.path.abspath(filename)
        if _APP_DIR and filename.startswith(_APP_DIR):
            _HITS[(filename, lineno)] = _HITS.get((filename, lineno), 0) + 1

    _tool = _mon.PROFILER_ID
    if _mon.get_tool(_tool) is None:
        _mon.use_tool_id(_tool, "shinycov_line_hits")
        _mon.register_callback(_tool, _mon.events.LINE, _line_cb)
        _mon.set_events(_tool, _mon.events.LINE)
except Exception:
    pass
'''


def install(out_dir: str | pathlib.Path) -> pathlib.Path:
    """Install the subprocess hook into `out_dir` and expose it via env vars.

    Writes `sitecustomize.py` (the hook source) and sets `PYTHONPATH` plus
    `SHINYCOV_OUTPUT_DIR` so the app subprocess imports the hook at startup
    and knows where to write `modules.json`.
    """
    out_dir = pathlib.Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "sitecustomize.py").write_text(SITE_CUSTOMIZE, encoding="utf-8")

    existing = os.environ.get("PYTHONPATH", "")
    os.environ["PYTHONPATH"] = (
        str(out_dir) + (os.pathsep + existing if existing else "")
    )
    os.environ["SHINYCOV_OUTPUT_DIR"] = str(out_dir)
    return out_dir


def read_line_hits(
    out_dir: str | pathlib.Path,
) -> dict[str, dict[tuple[str, int], int]]:
    """Read per-source line-hit counts written by the subprocess hook.

    Returns `{source: {(filename, line): count}}` where `count` is the
    number of times that line executed (the covr-style execution count
    coverage.py's own boolean line data does not retain).
    """
    out_dir = pathlib.Path(out_dir)
    result: dict[str, dict[tuple[str, int], int]] = {}
    for path in out_dir.glob("linehits.*.json"):
        source = path.name[len("linehits.") : -len(".json")]
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(data, dict):
            continue
        per_file: dict[tuple[str, int], int] = {}
        for key, count in data.items():
            filename, _, lineno = key.rpartition(":")
            if filename and lineno.isdigit() and isinstance(count, int):
                per_file[(filename, int(lineno))] = count
        result[source] = per_file
    return result


def read_boundaries(out_dir: str | pathlib.Path) -> list[str]:
    """Read the module boundaries written by the app subprocess hook."""
    path = pathlib.Path(out_dir) / "modules.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []
    return data if isinstance(data, list) else []


def attach_boundaries(
    snapshot: dict[str, Any], boundaries: list[str]
) -> dict[str, Any]:
    """Populate a manifest's `modules` and each element's `module` field.

    Longest-prefix match against the recorded boundaries, the same
    attribution R's `apply_module_boundaries()` performs. R's corroboration
    check (a lone id that merely shares a real module's prefix) is
    deliberately not ported: it only affects cosmetic grouping in a rare
    top-level-id-coincidence case.
    """
    if not boundaries:
        return snapshot
    ordered = sorted(set(boundaries), key=len, reverse=True)

    def owning(element_id: str) -> str:
        for boundary in ordered:
            if element_id == boundary or element_id.startswith(boundary + "-"):
                return boundary
        return ""

    snapshot["modules"] = sorted(set(boundaries))
    for element in snapshot.get("inputs", []):
        element["module"] = owning(element.get("id") or "")
    for element in snapshot.get("outputs", []):
        element["module"] = owning(element.get("id") or "")
    return snapshot
