#!/usr/bin/env python3
"""Vendor shiny.cov-r/inst/js/discover-bindings.js into this package.

Writes a generated Python module containing the source as a string
constant, so the pytest plugin evaluates the exact same UI-discovery
algorithm the R side does, rather than a hand-ported copy that could
drift from it. Mirrors shiny.cov-cypress/scripts/sync-discover-bindings.js.

Run from shiny.cov-py/: python scripts/sync_discover_bindings.py
"""
from __future__ import annotations

import pathlib

# Monorepo-relative: this script is a maintainer/dev-time tool that only
# ever runs from within a checkout containing both packages as siblings.
# It is never invoked by a pip consumer of the published package.
_HERE = pathlib.Path(__file__).resolve().parent
CANONICAL_PATH = _HERE.parent.parent / "shiny.cov-r" / "inst" / "js" / "discover-bindings.js"
OUTPUT_PATH = _HERE.parent / "src" / "shinycov" / "vendor" / "discover_bindings_source.py"

HEADER = (
    "# GENERATED by scripts/sync_discover_bindings.py from "
    "shiny.cov-r/inst/js/discover-bindings.js -- do not edit by hand, "
    "re-run the sync script instead.\n"
)


def render_vendored_module(source: str) -> str:
    """Render the generated module source for a given JS source string.

    Uses `repr()` rather than a triple-quoted/f-string wrap so arbitrary JS
    content -- backticks, quotes, backslashes, newlines -- round-trips
    safely regardless of what the canonical source happens to contain.
    """
    return HEADER + f"DISCOVER_BINDINGS_SOURCE = {source!r}\n"


def sync() -> pathlib.Path:
    source = CANONICAL_PATH.read_text(encoding="utf-8")
    rendered = render_vendored_module(source)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    return OUTPUT_PATH


if __name__ == "__main__":
    written = sync()
    print(f"Wrote {written}")
